apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fitches
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:5.5
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - name: data
        hostPath:
          path: /var/lib/pi-k8s/mysql
          type: DirectoryOrCreate
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: fitches
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306